version: '3.8'

services:
  client:
    image: whattodo-mevn-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: whattodo-mevn-frontend
    environment:
      BACKEND_URL: "/api/"

  server:
    image: whattodo-mevn-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    container_name: whattodo-mevn-backend
    environment:
      MONGO_URL: 'mongodb://the_username:the_password@mongo:27017/the_database'

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: whattodo-mevn-reverse-proxy

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    container_name: whattodo-mevn-mongo
    volumes: 
      - ./whattodo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./whattodo-backend/mongo_data:/data/db